[package]
name = "pyo3-asyncio-macros"
version = "0.13.0"
authors = ["Andrew J Westlake <awestlake87@yahoo.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1", features = ["full"] }